on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Disable AppArmor
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: cachix/cachix-action@v16
        with:
          name: zigplug
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build examples
        run: |
          for example in $(find $(realpath ..) -path "*/zigplug/examples/*/build.zig"); do
            cd $(dirname $example)
            nix develop -c zig build
          done
