on:
  push:
    paths:
      - "*.nix"
      - "flake.lock"
  pull_request:
    paths:
      - "*.nix"
      - "flake.lock"

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v3
        with:
          lix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}
          gc-max-store-size: 5G

      - name: Setup Nix cache
        uses: cachix/cachix-action@v16
        with:
          name: zigplug
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build devshell
        run: nix build .#devShells.$(nix eval --expr builtins.currentSystem --impure).default
