on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Run tests
        run: zig build test -Dclap

      - name: Build examples
        run: |
          for example in $(find $(realpath ..) -path "*/zigplug/examples/*/build.zig"); do
            cd $(dirname $example)
            zig build
          done
